version: '3.8'
services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka

  kafka:
    container_name: kafka
    hostname: kafka
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,DOCKER://kafka:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - kafka
    depends_on:
      - zookeeper

  app:
    container_name: app
    build: .
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - kafka

networks:
  kafka:
    driver: bridge